baseURL = 'https://biasedscala.github.io/'
languageCode = 'en-us'
title = 'Biased Scala'
# theme = "hugo-ink"
theme = "hyde"
# theme = "researcher"

[params]
  description = "My Baised Opinion on Scala"


[Menus]
  main = [
      {Name = "Blog", URL = "https://afoo.me"},
      {Name = "Twitter", URL = "https://twitter.com/fujohnwang"},
      {Name = "Github", URL = "https://github.com/fujohnwang/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/fujohnwang/"}
  ]